# Generated by Django 2.0.7 on 2018-07-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MJ_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Enter_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
